---
- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  
# Removing for pipx install
- name: "Remove Packages"
  package:
    name:
      - crackmapexec
      - certipy-ad
      - code-oss
    state: absent
  become: true
  become_method: sudo
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - exiftool
      - rsyslog
      - golang
      - ufw
    state: latest
  become: true
  become_method: sudo