---
- name: "Create RedTeam directories"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Documents/RedTeam/{{ item }}"
    state: directory
  loop:
    - PostExploit
    - Bin
    - PrivEsc
    - Pivoting
    - Shells
    - ActiveDirectory
    - Exfiltration
    - MiscTools/WordListsGen
    - MiscTools/Docker-Dive
    - Network/SNMP
    - Network/SMB
    - C2

- name: "Create Shells directories"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/{{ item }}"
    state: directory
  loop:
    - ASPX
    - PHP
    - SharedLib
    - DLL
    - Bash
    - PowerShell
    - Python
    - VBA

- name: "Create Linux directories"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Documents/RedTeam/PrivEsc/{{ item }}"
    state: directory
  loop:
    - Windows
    - Linux

- name: "Create Windows directories"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Documents/RedTeam/Pivoting/{{ item }}"
    state: directory
  loop:
    - Windows
    - Linux

- name: "Create Windows directories"
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/Documents/RedTeam/Pivoting/{{ PostExploit }}"
    state: directory
  loop:
    - Windows
    - Linux