---
- name: "Download Ngrok"
  ansible.builtin.shell:
    cmd: "wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O /tmp/ngrok-v3-stable-linux-amd64.tgz"

- name: "Install Ngrok"
  ansible.builtin.shell:
    cmd: "tar xvzf /tmp/ngrok-v3-stable-linux-amd64.tgz -C /home/{{ ansible_user_id }}/Documents/RedTeam/Linux/Pivoting/"

- name: "Wget Github binaries"
  ansible.builtin.shell:
    cmd: |
     wget https://github.com/int0x33/nc.exe/raw/master/nc.exe -O /home/{{ ansible_user_id }}/Documents/RedTeam/Windows/Pivoting/nc.exe
     wget https://github.com/int0x33/nc.exe/raw/master/nc64.exe -O /home/{{ ansible_user_id }}/Documents/RedTeam/Windows/Pivoting/nc64.exe
     wget https://github.com/andrew-d/static-binaries/raw/master/binaries/linux/x86_64/ncat -O /home/{{ ansible_user_id }}/Documents/RedTeam/Linux/Pivoting/ncat
     wget https://github.com/andrew-d/static-binaries/raw/master/binaries/linux/x86_64/socat -O /home/{{ ansible_user_id }}/Documents/RedTeam/Linux/Pivoting/socat
     wget https://github.com/andrew-d/static-binaries/raw/master/binaries/linux/x86_64/nmap -O /home/{{ ansible_user_id }}/Documents/RedTeam/Linux/Pivoting/nmap
     wget https://www.exploit-db.com/download/47163 -O /home/{{ ansible_user_id }}/Documents/RedTeam/Linux/PrivEsc/ExploitsLib/Polkit/Pkexec_PTRACE_TRACEME-CVE-2019-13272.c
     wget https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/master/Privesc/PowerUp.ps1 -O /home/{{ ansible_user_id }}/Documents/RedTeam/Windows/PrivEsc/PowerUp.ps1
     wget https://github.com/Re4son/Churrasco/raw/master/churrasco.exe -O /home/{{ ansible_user_id }}/Documents/RedTeam/Windows/PrivEsc/Potatoes/churrasco.exe
     mkdir /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/ASPX/
     mkdir /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PHP/
     mkdir /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/SharedLib/
     mkdir /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/DLL/
     wget https://raw.githubusercontent.com/borjmz/aspx-reverse-shell/master/shell.aspx -O /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/ASPX/reverse_shell.aspx
     wget https://raw.githubusercontent.com/xl7dev/WebShell/master/Aspx/awen%20asp.net%20webshell.aspx -O /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/ASPX/webshell.aspx
     wget https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php -O /home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PHP/reverse-shell.php

- name: "Copying reverse-shell-proc-open.php to RedTeam folder"
  copy:
    src: "files/reverse-shell-proc-open.php"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PHP/reverse-shell-proc-open.php"

- name: "Copying webshell.php to RedTeam folder"
  copy:
    src: "files/webshell.php"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PHP/webshell.php"

- name: "Copying iex-stagers.txt to RedTeam folder"
  copy:
    src: "files/iex-stagers.txt"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PowerShell/iex-stagers.txt"

- name: "Copying reverse-shell.ps1 to RedTeam folder"
  copy:
    src: "files/reverse-shell.ps1"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/PowerShell/reverse-shell.ps1"

- name: "Copying shared-library.c to RedTeam folder"
  copy:
    src: "files/shared-library.c"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/SharedLib/shared-library.c"

- name: "Copying template-windows-dll.c to RedTeam folder"
  copy:
    src: "files/template-windows-dll.c"
    dest: "/home/{{ ansible_user_id }}/Documents/RedTeam/Shells/DLL/template-windows-dll.c"